---
- include_vars: "group_vars/motherboards/{{ motherboard.stdout }}.yml"
  when: motherboard is defined

- name: "Install Galicaster Profiles"
  template: >
         src=profiles/{{ item }}
         dest=/etc/galicaster/profiles/{{ item }}
         group={{ ca_username }}
         owner={{ ca_username }}
  with_items:
         - dual-v4l2-split.ini
         - v4l2-split.ini
         - v4l2-usb.ini
  # notify: restart galicaster
  tags:
         - galicaster
         - galicaster_config
         - galicaster_profiles

- name: "Friendly device name configuration"
  template:
    src: "70-friendly-device-names.rules"
    dest: "/etc/udev/rules.d/70-friendly-device-names.rules"
    group: "root"
    owner: "root"
    mode: "0644"
  tags:
    - galicaster
    - galicaster_config
    - galicaster_profiles
    - v4l_devices

- name: "Set the line in source port for 'Stereo Input For Microphone'"
  shell: pactl --server={{ pa_server_name }} set-source-port {{ GC_line_in_source }} analog-input-headphone-mic
  become: true
  become_user: "{{ ca_username }}"
  tags: pactl_set_source_port
